import "@tok-wizard/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@tok-wizard/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@components/shadcn/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <TRPCReactProvider>
        <html lang="en">
          <body className={`font-sans ${inter.variable}`}>
            <main>{children}</main>
            <Toaster/>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
